create extension if not exists btree_gist with schema extensions;

create table public.booking_occupancies (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  event_key text not null,
  event_name text not null,
  property public.property not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status public.status not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_occupancies_valid_period check (starts_at < ends_at),
  constraint booking_occupancies_booking_event_property_key
    unique (booking_id, event_key, property)
);

comment on table public.booking_occupancies is
  'Normalized confirmed/preconfirmed property occupancy periods derived from the latest version of each booking.';

create index booking_occupancies_property_period_idx
  on public.booking_occupancies
  using gist (property, tstzrange(starts_at, ends_at, '[)'));

create index booking_occupancies_booking_id_idx
  on public.booking_occupancies (booking_id);

create index booking_occupancies_blocking_status_idx
  on public.booking_occupancies (status)
  where status in ('confirmed', 'preconfirmed');

alter table public.booking_occupancies enable row level security;

revoke all on table public.booking_occupancies from anon, authenticated;
revoke all on sequence public.booking_occupancies_id_seq from anon, authenticated;

create or replace function public.find_booking_conflicts(
  candidate_occupancies jsonb,
  excluded_booking_id bigint default null
)
returns table (
  conflict_booking_id bigint,
  client_name text,
  conflict_status public.status,
  event_key text,
  event_name text,
  property public.property,
  existing_starts_at timestamptz,
  existing_ends_at timestamptz,
  overlap_starts_at timestamptz,
  overlap_ends_at timestamptz
)
language sql
stable
set search_path = ''
as $$
  select distinct
    existing.booking_id,
    booking.client_name,
    existing.status,
    existing.event_key,
    existing.event_name,
    existing.property,
    existing.starts_at,
    existing.ends_at,
    greatest(existing.starts_at, candidate."startsAt"),
    least(existing.ends_at, candidate."endsAt")
  from jsonb_to_recordset(candidate_occupancies) as candidate(
    "eventKey" text,
    "eventName" text,
    property text,
    "startsAt" timestamptz,
    "endsAt" timestamptz,
    status text
  )
  join public.booking_occupancies existing
    on existing.property = candidate.property::public.property
   and existing.starts_at < candidate."endsAt"
   and candidate."startsAt" < existing.ends_at
  join public.bookings booking
    on booking.id = existing.booking_id
  where candidate.status in ('confirmed', 'preconfirmed')
    and existing.status in ('confirmed', 'preconfirmed')
    and (
      excluded_booking_id is null
      or existing.booking_id <> excluded_booking_id
    )
  order by
    greatest(existing.starts_at, candidate."startsAt"),
    existing.property,
    existing.booking_id,
    existing.event_key;
$$;

comment on function public.find_booking_conflicts(jsonb, bigint) is
  'Returns every blocking Supabase reservation period that overlaps candidate occupancies.';

revoke all on function public.find_booking_conflicts(jsonb, bigint) from public, anon, authenticated;
grant execute on function public.find_booking_conflicts(jsonb, bigint) to service_role;

create or replace function public.audit_booking_conflicts(
  include_historical boolean default true,
  as_of timestamptz default now()
)
returns table (
  first_booking_id bigint,
  first_client_name text,
  first_status public.status,
  first_event_key text,
  first_event_name text,
  first_starts_at timestamptz,
  first_ends_at timestamptz,
  second_booking_id bigint,
  second_client_name text,
  second_status public.status,
  second_event_key text,
  second_event_name text,
  second_starts_at timestamptz,
  second_ends_at timestamptz,
  property public.property,
  overlap_starts_at timestamptz,
  overlap_ends_at timestamptz,
  historical boolean
)
language sql
stable
set search_path = ''
as $$
  select
    first_occupancy.booking_id,
    first_booking.client_name,
    first_occupancy.status,
    first_occupancy.event_key,
    first_occupancy.event_name,
    first_occupancy.starts_at,
    first_occupancy.ends_at,
    second_occupancy.booking_id,
    second_booking.client_name,
    second_occupancy.status,
    second_occupancy.event_key,
    second_occupancy.event_name,
    second_occupancy.starts_at,
    second_occupancy.ends_at,
    first_occupancy.property,
    greatest(first_occupancy.starts_at, second_occupancy.starts_at),
    least(first_occupancy.ends_at, second_occupancy.ends_at),
    least(first_occupancy.ends_at, second_occupancy.ends_at) < as_of
  from public.booking_occupancies first_occupancy
  join public.booking_occupancies second_occupancy
    on first_occupancy.booking_id < second_occupancy.booking_id
   and first_occupancy.property = second_occupancy.property
   and first_occupancy.starts_at < second_occupancy.ends_at
   and second_occupancy.starts_at < first_occupancy.ends_at
  join public.bookings first_booking
    on first_booking.id = first_occupancy.booking_id
  join public.bookings second_booking
    on second_booking.id = second_occupancy.booking_id
  where first_occupancy.status in ('confirmed', 'preconfirmed')
    and second_occupancy.status in ('confirmed', 'preconfirmed')
    and (
      include_historical
      or least(first_occupancy.ends_at, second_occupancy.ends_at) >= as_of
    )
  order by
    greatest(first_occupancy.starts_at, second_occupancy.starts_at),
    first_occupancy.property,
    first_occupancy.booking_id,
    second_occupancy.booking_id;
$$;

comment on function public.audit_booking_conflicts(boolean, timestamptz) is
  'Audits all confirmed/preconfirmed booking pairs with overlapping property occupancy.';

revoke all on function public.audit_booking_conflicts(boolean, timestamptz)
  from public, anon, authenticated;
grant execute on function public.audit_booking_conflicts(boolean, timestamptz)
  to service_role;

-- Do not add the exclusion constraint until existing data has been backfilled,
-- audited, and reconciled. The follow-up constraint should use:
--
-- alter table public.booking_occupancies
--   add constraint booking_occupancies_no_blocking_overlap
--   exclude using gist (
--     property with =,
--     tstzrange(starts_at, ends_at, '[)') with &&
--   )
--   where (status in ('confirmed', 'preconfirmed'));
