create table public.booking_cost_items (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  property public.property,
  event_id bigint,
  item_type text not null check (item_type in ('cost', 'tax')),
  name text not null,
  amount numeric not null check (amount >= 0)
);

create index booking_cost_items_booking_id_idx
  on public.booking_cost_items (booking_id);

create index booking_cost_items_property_idx
  on public.booking_cost_items (property);

create table public.booking_payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  amount numeric not null check (amount >= 0),
  payment_method text not null,
  payment_date timestamptz not null,
  received_by jsonb,
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object')
);

create index booking_payments_booking_id_idx
  on public.booking_payments (booking_id);

create table public.booking_security_deposits (
  booking_id bigint primary key references public.bookings(id) on delete cascade,
  amount numeric not null check (amount >= 0),
  payment_method text not null,
  amount_returned numeric not null default 0 check (amount_returned >= 0),
  date_returned timestamptz
);

create view public.booking_financial_totals
with (security_invoker = true)
as
with item_totals as (
  select
    booking_id,
    coalesce(sum(amount) filter (where item_type = 'cost'), 0) as total_cost,
    coalesce(sum(amount) filter (where item_type = 'tax'), 0) as tax
  from public.booking_cost_items
  group by booking_id
),
payment_totals as (
  select booking_id, coalesce(sum(amount), 0) as paid
  from public.booking_payments
  group by booking_id
)
select
  booking.id as booking_id,
  coalesce(item.total_cost, 0) as total_cost,
  coalesce(item.tax, 0) as tax,
  coalesce(item.total_cost, 0) + coalesce(item.tax, 0) as after_tax_total,
  coalesce(payment.paid, 0) as paid,
  coalesce(item.total_cost, 0) + coalesce(item.tax, 0)
    - coalesce(payment.paid, 0) as outstanding
from public.bookings booking
left join item_totals item on item.booking_id = booking.id
left join payment_totals payment on payment.booking_id = booking.id;

alter table public.booking_cost_items enable row level security;
alter table public.booking_payments enable row level security;
alter table public.booking_security_deposits enable row level security;

revoke all on table public.booking_cost_items from anon, authenticated;
revoke all on table public.booking_payments from anon, authenticated;
revoke all on table public.booking_security_deposits from anon, authenticated;
revoke all on table public.booking_financial_totals from anon, authenticated;

grant all on table public.booking_cost_items to service_role;
grant all on table public.booking_payments to service_role;
grant all on table public.booking_security_deposits to service_role;
grant select on table public.booking_financial_totals to service_role;

grant usage, select on sequence public.booking_cost_items_id_seq to service_role;
grant usage, select on sequence public.booking_payments_id_seq to service_role;
